# Generated by Django 5.1.2 on 2024-12-05 22:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currencyName', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('itemID', models.UUIDField(default=uuid.UUID('42147709-f30c-4a37-ab97-2fee14f05887'), editable=False, primary_key=True, serialize=False)),
                ('itemName', models.CharField(max_length=20)),
                ('itemPriceInCents', models.IntegerField()),
                ('itemsToReceiveAfterIAP', models.JSONField(default=dict)),
                ('itemsReceivedAmountAfterIAP', models.JSONField(default=dict)),
            ],
        ),
    ]
