# Generated by Django 5.1.2 on 2024-12-05 22:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='itemID',
            field=models.UUIDField(default=uuid.UUID('3421fed5-be78-49b4-b2a6-5752e3907217'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='shopitem',
            name='itemsToReceiveAfterIAP',
        ),
        migrations.AddField(
            model_name='shopitem',
            name='itemsToReceiveAfterIAP',
            field=models.ManyToManyField(to='Shop.gamecurrency'),
        ),
    ]
