# Generated by Django 5.1.2 on 2024-12-05 22:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_alter_shopitem_itemid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='itemID',
            field=models.UUIDField(default=uuid.UUID('f025c49f-4281-480b-9293-1b4fba6da9c6'), editable=False, primary_key=True, serialize=False),
        ),
    ]
